# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-11 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physician', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physician',
            name='contact',
            field=models.IntegerField(default=9121455080L),
        ),
    ]
